// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrhTs7dFEUVAcZGKCGEoa31WGQ9YvWv6k',
    appId: '1:34198666131:web:e79217636975fa631c8666',
    messagingSenderId: '34198666131',
    projectId: 'starmail-agenda',
    authDomain: 'starmail-agenda.firebaseapp.com',
    storageBucket: 'starmail-agenda.appspot.com',
    measurementId: 'G-TL7199JS32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyYSPOaygn2slJZp5kapXN48NAlplnPu8',
    appId: '1:34198666131:android:38480e00caec11bb1c8666',
    messagingSenderId: '34198666131',
    projectId: 'starmail-agenda',
    storageBucket: 'starmail-agenda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnDAUq4d_C1TGmpeFBQSwYzeiqCKSmhr4',
    appId: '1:34198666131:ios:ccdd6995f04861e81c8666',
    messagingSenderId: '34198666131',
    projectId: 'starmail-agenda',
    storageBucket: 'starmail-agenda.appspot.com',
    iosBundleId: 'com.example.recipes',
  );
}
